Javadoc reservation
Cisfinitum/FirstProject pull request #101
Opened 2019-03-05 19:41 UTC by MaltsevaKsenia

2019-03-05 20:11 UTC, ghost approved these changes

2019-03-05 20:11 UTC, imbirevkotlya commented on src/main/java/com/epam/controller/ClientsController.java
> +    private final ReservationServiceImpl reservationServiceImpl;
You can autowire interfaces, it is spring dependency injection magic))

2019-03-05 20:11 UTC, ghost requested changes
see the comment above

2019-03-06 08:37 UTC, goponenkoev approved these changes

2019-03-06 10:59 UTC, closed without merging