Fix offer controller
Cisfinitum/FirstProject pull request #49
Opened 2019-02-21 16:40 UTC by VNTee

Add green color for "success" message

2019-02-21 18:55 UTC, MaltsevaKsenia approved these changes

2019-02-22 10:22 UTC, goponenkoev approved these changes

2019-02-22 14:17 UTC, grigiv approved these changes

2019-02-22 16:24 UTC, ghost requested changes

2019-02-22 16:24 UTC, imbirevkotlya commented on src/main/java/com/epam/controller/ToursController.java
> +        toursModel.addObject("result","Success");
Oh my God, what happen with code style here??????

2019-02-22 16:24 UTC, imbirevkotlya commented on src/main/java/com/epam/controller/ToursController.java
> +                toursModel.addObject("result","Success");
please follow java code conventions! It is not readable code

2019-02-22 18:35 UTC, ghost approved these changes

2019-02-23 17:15 UTC, merged