Edit readme
Cisfinitum/FirstProject pull request #83
Opened 2019-03-02 16:23 UTC by MaltsevaKsenia

2019-03-02 17:26 UTC, ghost requested changes

2019-03-02 17:26 UTC, imbirevkotlya commented on README.md
> + >apply plugin: 'com.bmuschko.tomcat'
can you please refactor this part, to make it just like a code snippet
see an example here: https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

2019-03-02 17:26 UTC, imbirevkotlya commented on README.md
> + >apply plugin: 'com.bmuschko.tomcat'
https://help.github.com/en/articles/creating-and-highlighting-code-blocks

2019-03-03 18:52 UTC, ghost approved these changes

2019-03-03 20:06 UTC, goponenkoev approved these changes

2019-03-04 08:56 UTC, Cisfinitum approved these changes

2019-03-04 11:38 UTC, grigiv approved these changes

2019-03-04 11:48 UTC, VNTee approved these changes

2019-03-04 12:00 UTC, merged